//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MaloncosModel", "C4", "Articles", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Maloncos.Models.Articles), "Ligne_commande", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Maloncos.Models.Ligne_commande), true)]
[assembly: EdmRelationshipAttribute("MaloncosModel", "C5", "Clients", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Maloncos.Models.Clients), "Ligne_commande", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Maloncos.Models.Ligne_commande), true)]
[assembly: EdmRelationshipAttribute("MaloncosModel", "C7", "Clients", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Maloncos.Models.Clients), "Compte", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Maloncos.Models.Compte), true)]
[assembly: EdmRelationshipAttribute("MaloncosModel", "C6", "Commande", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Maloncos.Models.Commande), "Ligne_commande", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Maloncos.Models.Ligne_commande), true)]

#endregion

namespace Maloncos.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MaloncosEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MaloncosEntities1 object using the connection string found in the 'MaloncosEntities1' section of the application configuration file.
        /// </summary>
        public MaloncosEntities1() : base("name=MaloncosEntities1", "MaloncosEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MaloncosEntities1 object.
        /// </summary>
        public MaloncosEntities1(string connectionString) : base(connectionString, "MaloncosEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MaloncosEntities1 object.
        /// </summary>
        public MaloncosEntities1(EntityConnection connection) : base(connection, "MaloncosEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Articles> Articles
        {
            get
            {
                if ((_Articles == null))
                {
                    _Articles = base.CreateObjectSet<Articles>("Articles");
                }
                return _Articles;
            }
        }
        private ObjectSet<Articles> _Articles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Clients> Clients
        {
            get
            {
                if ((_Clients == null))
                {
                    _Clients = base.CreateObjectSet<Clients>("Clients");
                }
                return _Clients;
            }
        }
        private ObjectSet<Clients> _Clients;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Commande> Commande
        {
            get
            {
                if ((_Commande == null))
                {
                    _Commande = base.CreateObjectSet<Commande>("Commande");
                }
                return _Commande;
            }
        }
        private ObjectSet<Commande> _Commande;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Compte> Compte
        {
            get
            {
                if ((_Compte == null))
                {
                    _Compte = base.CreateObjectSet<Compte>("Compte");
                }
                return _Compte;
            }
        }
        private ObjectSet<Compte> _Compte;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ligne_commande> Ligne_commande
        {
            get
            {
                if ((_Ligne_commande == null))
                {
                    _Ligne_commande = base.CreateObjectSet<Ligne_commande>("Ligne_commande");
                }
                return _Ligne_commande;
            }
        }
        private ObjectSet<Ligne_commande> _Ligne_commande;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Articles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToArticles(Articles articles)
        {
            base.AddObject("Articles", articles);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Clients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClients(Clients clients)
        {
            base.AddObject("Clients", clients);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Commande EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCommande(Commande commande)
        {
            base.AddObject("Commande", commande);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Compte EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCompte(Compte compte)
        {
            base.AddObject("Compte", compte);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ligne_commande EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLigne_commande(Ligne_commande ligne_commande)
        {
            base.AddObject("Ligne_commande", ligne_commande);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MaloncosModel", Name="Articles")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Articles : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Articles object.
        /// </summary>
        /// <param name="num_Articles">Initial value of the Num_Articles property.</param>
        /// <param name="libelle">Initial value of the Libelle property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="composition">Initial value of the Composition property.</param>
        /// <param name="taille">Initial value of the Taille property.</param>
        /// <param name="couleur">Initial value of the Couleur property.</param>
        /// <param name="prix_Article">Initial value of the Prix_Article property.</param>
        /// <param name="image">Initial value of the Image property.</param>
        /// <param name="categorie">Initial value of the Categorie property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        public static Articles CreateArticles(global::System.Int32 num_Articles, global::System.String libelle, global::System.String description, global::System.String composition, global::System.Int32 taille, global::System.String couleur, global::System.Decimal prix_Article, global::System.String image, global::System.String categorie, global::System.String type)
        {
            Articles articles = new Articles();
            articles.Num_Articles = num_Articles;
            articles.Libelle = libelle;
            articles.Description = description;
            articles.Composition = composition;
            articles.Taille = taille;
            articles.Couleur = couleur;
            articles.Prix_Article = prix_Article;
            articles.Image = image;
            articles.Categorie = categorie;
            articles.Type = type;
            return articles;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Num_Articles
        {
            get
            {
                return _Num_Articles;
            }
            set
            {
                if (_Num_Articles != value)
                {
                    OnNum_ArticlesChanging(value);
                    ReportPropertyChanging("Num_Articles");
                    _Num_Articles = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Num_Articles");
                    OnNum_ArticlesChanged();
                }
            }
        }
        private global::System.Int32 _Num_Articles;
        partial void OnNum_ArticlesChanging(global::System.Int32 value);
        partial void OnNum_ArticlesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Libelle
        {
            get
            {
                return _Libelle;
            }
            set
            {
                OnLibelleChanging(value);
                ReportPropertyChanging("Libelle");
                _Libelle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Libelle");
                OnLibelleChanged();
            }
        }
        private global::System.String _Libelle;
        partial void OnLibelleChanging(global::System.String value);
        partial void OnLibelleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Composition
        {
            get
            {
                return _Composition;
            }
            set
            {
                OnCompositionChanging(value);
                ReportPropertyChanging("Composition");
                _Composition = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Composition");
                OnCompositionChanged();
            }
        }
        private global::System.String _Composition;
        partial void OnCompositionChanging(global::System.String value);
        partial void OnCompositionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Taille
        {
            get
            {
                return _Taille;
            }
            set
            {
                OnTailleChanging(value);
                ReportPropertyChanging("Taille");
                _Taille = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Taille");
                OnTailleChanged();
            }
        }
        private global::System.Int32 _Taille;
        partial void OnTailleChanging(global::System.Int32 value);
        partial void OnTailleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Couleur
        {
            get
            {
                return _Couleur;
            }
            set
            {
                OnCouleurChanging(value);
                ReportPropertyChanging("Couleur");
                _Couleur = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Couleur");
                OnCouleurChanged();
            }
        }
        private global::System.String _Couleur;
        partial void OnCouleurChanging(global::System.String value);
        partial void OnCouleurChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Prix_Article
        {
            get
            {
                return _Prix_Article;
            }
            set
            {
                OnPrix_ArticleChanging(value);
                ReportPropertyChanging("Prix_Article");
                _Prix_Article = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Prix_Article");
                OnPrix_ArticleChanged();
            }
        }
        private global::System.Decimal _Prix_Article;
        partial void OnPrix_ArticleChanging(global::System.Decimal value);
        partial void OnPrix_ArticleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Image
        {
            get
            {
                return _Image;
            }
            set
            {
                OnImageChanging(value);
                ReportPropertyChanging("Image");
                _Image = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Image");
                OnImageChanged();
            }
        }
        private global::System.String _Image;
        partial void OnImageChanging(global::System.String value);
        partial void OnImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Categorie
        {
            get
            {
                return _Categorie;
            }
            set
            {
                OnCategorieChanging(value);
                ReportPropertyChanging("Categorie");
                _Categorie = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Categorie");
                OnCategorieChanged();
            }
        }
        private global::System.String _Categorie;
        partial void OnCategorieChanging(global::System.String value);
        partial void OnCategorieChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MaloncosModel", "C4", "Ligne_commande")]
        public EntityCollection<Ligne_commande> Ligne_commande
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ligne_commande>("MaloncosModel.C4", "Ligne_commande");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ligne_commande>("MaloncosModel.C4", "Ligne_commande", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MaloncosModel", Name="Clients")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Clients : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Clients object.
        /// </summary>
        /// <param name="num_Client">Initial value of the Num_Client property.</param>
        /// <param name="nom">Initial value of the Nom property.</param>
        /// <param name="prenom">Initial value of the Prenom property.</param>
        /// <param name="adresse1">Initial value of the Adresse1 property.</param>
        public static Clients CreateClients(global::System.Int32 num_Client, global::System.String nom, global::System.String prenom, global::System.String adresse1)
        {
            Clients clients = new Clients();
            clients.Num_Client = num_Client;
            clients.Nom = nom;
            clients.Prenom = prenom;
            clients.Adresse1 = adresse1;
            return clients;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Num_Client
        {
            get
            {
                return _Num_Client;
            }
            set
            {
                if (_Num_Client != value)
                {
                    OnNum_ClientChanging(value);
                    ReportPropertyChanging("Num_Client");
                    _Num_Client = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Num_Client");
                    OnNum_ClientChanged();
                }
            }
        }
        private global::System.Int32 _Num_Client;
        partial void OnNum_ClientChanging(global::System.Int32 value);
        partial void OnNum_ClientChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nom
        {
            get
            {
                return _Nom;
            }
            set
            {
                OnNomChanging(value);
                ReportPropertyChanging("Nom");
                _Nom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nom");
                OnNomChanged();
            }
        }
        private global::System.String _Nom;
        partial void OnNomChanging(global::System.String value);
        partial void OnNomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Prenom
        {
            get
            {
                return _Prenom;
            }
            set
            {
                OnPrenomChanging(value);
                ReportPropertyChanging("Prenom");
                _Prenom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Prenom");
                OnPrenomChanged();
            }
        }
        private global::System.String _Prenom;
        partial void OnPrenomChanging(global::System.String value);
        partial void OnPrenomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Adresse1
        {
            get
            {
                return _Adresse1;
            }
            set
            {
                OnAdresse1Changing(value);
                ReportPropertyChanging("Adresse1");
                _Adresse1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Adresse1");
                OnAdresse1Changed();
            }
        }
        private global::System.String _Adresse1;
        partial void OnAdresse1Changing(global::System.String value);
        partial void OnAdresse1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Adresse2
        {
            get
            {
                return _Adresse2;
            }
            set
            {
                OnAdresse2Changing(value);
                ReportPropertyChanging("Adresse2");
                _Adresse2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Adresse2");
                OnAdresse2Changed();
            }
        }
        private global::System.String _Adresse2;
        partial void OnAdresse2Changing(global::System.String value);
        partial void OnAdresse2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telephone
        {
            get
            {
                return _Telephone;
            }
            set
            {
                OnTelephoneChanging(value);
                ReportPropertyChanging("Telephone");
                _Telephone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telephone");
                OnTelephoneChanged();
            }
        }
        private global::System.String _Telephone;
        partial void OnTelephoneChanging(global::System.String value);
        partial void OnTelephoneChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MaloncosModel", "C5", "Ligne_commande")]
        public EntityCollection<Ligne_commande> Ligne_commande
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ligne_commande>("MaloncosModel.C5", "Ligne_commande");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ligne_commande>("MaloncosModel.C5", "Ligne_commande", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MaloncosModel", "C7", "Compte")]
        public EntityCollection<Compte> Compte
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Compte>("MaloncosModel.C7", "Compte");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Compte>("MaloncosModel.C7", "Compte", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MaloncosModel", Name="Commande")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Commande : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Commande object.
        /// </summary>
        /// <param name="num_Commande">Initial value of the Num_Commande property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        public static Commande CreateCommande(global::System.Int32 num_Commande, global::System.DateTime date)
        {
            Commande commande = new Commande();
            commande.Num_Commande = num_Commande;
            commande.Date = date;
            return commande;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Num_Commande
        {
            get
            {
                return _Num_Commande;
            }
            set
            {
                if (_Num_Commande != value)
                {
                    OnNum_CommandeChanging(value);
                    ReportPropertyChanging("Num_Commande");
                    _Num_Commande = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Num_Commande");
                    OnNum_CommandeChanged();
                }
            }
        }
        private global::System.Int32 _Num_Commande;
        partial void OnNum_CommandeChanging(global::System.Int32 value);
        partial void OnNum_CommandeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MaloncosModel", "C6", "Ligne_commande")]
        public EntityCollection<Ligne_commande> Ligne_commande
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ligne_commande>("MaloncosModel.C6", "Ligne_commande");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ligne_commande>("MaloncosModel.C6", "Ligne_commande", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MaloncosModel", Name="Compte")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Compte : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Compte object.
        /// </summary>
        /// <param name="num_Compte">Initial value of the Num_Compte property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="num_Client">Initial value of the Num_Client property.</param>
        public static Compte CreateCompte(global::System.Int32 num_Compte, global::System.DateTime date, global::System.Int32 num_Client)
        {
            Compte compte = new Compte();
            compte.Num_Compte = num_Compte;
            compte.Date = date;
            compte.Num_Client = num_Client;
            return compte;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Num_Compte
        {
            get
            {
                return _Num_Compte;
            }
            set
            {
                if (_Num_Compte != value)
                {
                    OnNum_CompteChanging(value);
                    ReportPropertyChanging("Num_Compte");
                    _Num_Compte = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Num_Compte");
                    OnNum_CompteChanged();
                }
            }
        }
        private global::System.Int32 _Num_Compte;
        partial void OnNum_CompteChanging(global::System.Int32 value);
        partial void OnNum_CompteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Num_Client
        {
            get
            {
                return _Num_Client;
            }
            set
            {
                OnNum_ClientChanging(value);
                ReportPropertyChanging("Num_Client");
                _Num_Client = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Num_Client");
                OnNum_ClientChanged();
            }
        }
        private global::System.Int32 _Num_Client;
        partial void OnNum_ClientChanging(global::System.Int32 value);
        partial void OnNum_ClientChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MaloncosModel", "C7", "Clients")]
        public Clients Clients
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clients>("MaloncosModel.C7", "Clients").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clients>("MaloncosModel.C7", "Clients").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Clients> ClientsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clients>("MaloncosModel.C7", "Clients");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Clients>("MaloncosModel.C7", "Clients", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MaloncosModel", Name="Ligne_commande")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ligne_commande : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ligne_commande object.
        /// </summary>
        /// <param name="num_Article">Initial value of the Num_Article property.</param>
        /// <param name="num_Client">Initial value of the Num_Client property.</param>
        /// <param name="num_Commande">Initial value of the Num_Commande property.</param>
        /// <param name="quantite">Initial value of the Quantite property.</param>
        public static Ligne_commande CreateLigne_commande(global::System.Int32 num_Article, global::System.Int32 num_Client, global::System.Int32 num_Commande, global::System.String quantite)
        {
            Ligne_commande ligne_commande = new Ligne_commande();
            ligne_commande.Num_Article = num_Article;
            ligne_commande.Num_Client = num_Client;
            ligne_commande.Num_Commande = num_Commande;
            ligne_commande.Quantite = quantite;
            return ligne_commande;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Num_Article
        {
            get
            {
                return _Num_Article;
            }
            set
            {
                if (_Num_Article != value)
                {
                    OnNum_ArticleChanging(value);
                    ReportPropertyChanging("Num_Article");
                    _Num_Article = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Num_Article");
                    OnNum_ArticleChanged();
                }
            }
        }
        private global::System.Int32 _Num_Article;
        partial void OnNum_ArticleChanging(global::System.Int32 value);
        partial void OnNum_ArticleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Num_Client
        {
            get
            {
                return _Num_Client;
            }
            set
            {
                if (_Num_Client != value)
                {
                    OnNum_ClientChanging(value);
                    ReportPropertyChanging("Num_Client");
                    _Num_Client = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Num_Client");
                    OnNum_ClientChanged();
                }
            }
        }
        private global::System.Int32 _Num_Client;
        partial void OnNum_ClientChanging(global::System.Int32 value);
        partial void OnNum_ClientChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Num_Commande
        {
            get
            {
                return _Num_Commande;
            }
            set
            {
                if (_Num_Commande != value)
                {
                    OnNum_CommandeChanging(value);
                    ReportPropertyChanging("Num_Commande");
                    _Num_Commande = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Num_Commande");
                    OnNum_CommandeChanged();
                }
            }
        }
        private global::System.Int32 _Num_Commande;
        partial void OnNum_CommandeChanging(global::System.Int32 value);
        partial void OnNum_CommandeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Quantite
        {
            get
            {
                return _Quantite;
            }
            set
            {
                if (_Quantite != value)
                {
                    OnQuantiteChanging(value);
                    ReportPropertyChanging("Quantite");
                    _Quantite = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Quantite");
                    OnQuantiteChanged();
                }
            }
        }
        private global::System.String _Quantite;
        partial void OnQuantiteChanging(global::System.String value);
        partial void OnQuantiteChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MaloncosModel", "C4", "Articles")]
        public Articles Articles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Articles>("MaloncosModel.C4", "Articles").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Articles>("MaloncosModel.C4", "Articles").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Articles> ArticlesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Articles>("MaloncosModel.C4", "Articles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Articles>("MaloncosModel.C4", "Articles", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MaloncosModel", "C5", "Clients")]
        public Clients Clients
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clients>("MaloncosModel.C5", "Clients").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clients>("MaloncosModel.C5", "Clients").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Clients> ClientsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clients>("MaloncosModel.C5", "Clients");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Clients>("MaloncosModel.C5", "Clients", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MaloncosModel", "C6", "Commande")]
        public Commande Commande
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Commande>("MaloncosModel.C6", "Commande").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Commande>("MaloncosModel.C6", "Commande").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Commande> CommandeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Commande>("MaloncosModel.C6", "Commande");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Commande>("MaloncosModel.C6", "Commande", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
